### ISSUE TITLE
Failed subscribing to eventlog

### ISSUE THREAD

**Issue by SupraOva** [r-smith/sysmon-watcher#1]
Hello,

I wanted to try Sysmon-Watcher but when I launched it I got an error

![2023-07-19_17-05-19](https://github.com/r-smith/sysmon-watcher/assets/34113761/dbe87623-8fcd-4762-9374-01d3c238583d)

Version : 1.0.0
OS : Microsoft Windows Server 2012 R2 Standard (6.3.9600)

Thanks!

**Comment by r-smith** [comment]
Do you have Sysmon installed? This tool is meant to monitor logs generated by Sysmon (https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon).

**Comment by SupraOva** [comment]
Working after installing sysmon! Thanks

`sysmon -accepteula -i`

_PS : You should add it to the Readme_ 😉

**Comment by r-smith** [comment]
Nice! The default sysmon install won't log much. Here's some starter configs here https://github.com/SwiftOnSecurity/sysmon-config or here https://github.com/olafhartong/sysmon-modular. Get one of their xml files and do `sysmon -c <path-to-xml-config>`.

I'll clarify in the readme
